DB_HOST = "gateway01.eu-central-1.prod.aws.tidbcloud.com"
DB_PORT = 4000
DB_USER = "rokiKLn3USmrdLy.root"
DB_PASSWORD = "JSDkSTRt28CdzRja"
DB_NAME = "kletterdb"
OPENCAGE_KEY = "712b1c0ba9de4809898ffb646be05085"